# This is a basic workflow to help you get started with Actions

name: Tests
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install enviroment
        run: composer install
      # Runs a single command using the runners shell
      - name: Run tests
        run: make test
